// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF6uZ0J4Ai2j9z4dVizgy4LHtY4QANJ5M',
    appId: '1:229067710309:web:7fca3e2520c5b1c126cb8c',
    messagingSenderId: '229067710309',
    projectId: 'startinvest-72bc8',
    authDomain: 'startinvest-72bc8.firebaseapp.com',
    storageBucket: 'startinvest-72bc8.firebasestorage.app',
    measurementId: 'G-KRLV2JY2ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnBMUOLOoU7-Snnd6q9a4rs7BhwtpO2PI',
    appId: '1:229067710309:android:667a121d6dafb67926cb8c',
    messagingSenderId: '229067710309',
    projectId: 'startinvest-72bc8',
    storageBucket: 'startinvest-72bc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANoI5dMb1-rx388zt4dnMV4zeOdpdx624',
    appId: '1:229067710309:ios:d9ecc884a8456ae226cb8c',
    messagingSenderId: '229067710309',
    projectId: 'startinvest-72bc8',
    storageBucket: 'startinvest-72bc8.firebasestorage.app',
    androidClientId: '229067710309-j7absrqei27adaips5clr2oth1ungmia.apps.googleusercontent.com',
    iosClientId: '229067710309-am2k534c2pv6pcka46vmsprgdrin27gt.apps.googleusercontent.com',
    iosBundleId: 'com.startinvest.startinvest',
  );

}