sonar.projectKey=GHuemer_StartInvest
sonar.organization=ghuemer

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.coverageReportPaths=coverage/lcov.info

sonar.exclusions=\
  **/*.g.dart,\
  **/*.freezed.dart,\
  **/*.config.dart,\
  **/*.gr.dart,\
  **/generated/**,\
  lib/firebase_options.dart

sonar.coverage.exclusions=\
  **/*.g.dart,\
  **/*.freezed.dart,\
  **/*.config.dart,\
  **/*.gr.dart,\
  **/generated/**,\
  lib/firebase_options.dart,\
  lib/main.dart,\
  lib/core/di/**,\
  lib/core/router/**
